name: Firebase deployment

on:
  push:
    branches:
      - main


jobs:
  deploy:
    name: Build & deployment
    runs-on: ubuntu-latest

    steps:
      - name: get the source code
        uses: action/checkout@v2

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: install node pacakes
        run: npm i

      - name: Build
        uses: npm run build
        env: 
          CI: false
      
      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
